export const BACKEND_API = 'http://127.0.0.1:3000';
export const TOKEN_KEY = 'another dummy value';
export const ETHNICITY = [
    'African-American',
    'American Indian or Alaska Native',
    'Asian or Pacific Islander',
    'Caucasian',
    'Hispanic or Latino',
    'Multiracial',
    'Other',
    'Prefer not to answer',
];

export const ETHNICITY_SHORT = [
    'African-American',
    'Native American',
    'Asian or Pacific Islander',
    'Caucasian',
    'Hispanic or Latino',
    'Multiracial',
    'Other',
    'Not Disclosed',
];

export const DEVICE_TYPE = [
    'ANDROID',
    'DESKTOP/LAPTOP',
    'IPAD',
    'IPHONE'
];

export const US_STATES_STATE_CODES = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
];

export const US_STATES = [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "District of Columbia",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming"
    ];

export const EDUCATION = [
    'Less than high school',
    'High school graduate',
    'Some college',
    "Bachelor\'s degree",
    'Graduate degree',
    
];

export const GENDER = [
    'Female',
    'Male'
];
